name: Generate Terraform Documentation

permissions:
  contents: write

on:
  push:
    branches: [master]
    paths:
      - '**/*.tf'
  pull_request:
    branches: [master]
    paths:
      - '**/*.tf'

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Render terraform docs
        uses: Terraform-docs/gh-actions@v0.17.0
        with:
          working-dir: .
          output-file: README.md
          output-method: inject
          git-push: "true"
